spring.application.name=demo_spring_boot_ver3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/myjpa?serverTimezone=Asia/Taipei&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=springboot
spring.jpa.show-sql=true